package ch.epfl.sdp.database.dao

import android.util.Log
import androidx.lifecycle.MutableLiveData
import ch.epfl.sdp.database.data.SearchGroupData
import ch.epfl.sdp.database.data.UserData
import com.google.firebase.database.*
import com.google.firebase.database.ktx.database
import com.google.firebase.ktx.Firebase
import timber.log.Timber

class FirebaseGroupDao : SearchGroupDao {
    private var database: FirebaseDatabase = Firebase.database

    private val groups: MutableLiveData<List<SearchGroupData>> = MutableLiveData(mutableListOf())
    private val watchedGroupsById: MutableMap<String, MutableLiveData<SearchGroupData>> = mutableMapOf()

    override fun getGroups(): MutableLiveData<List<SearchGroupData>> {
        val myRef = database.getReference("search_groups")
        myRef.addValueEventListener(object : ValueEventListener {
            override fun onDataChange(dataSnapshot: DataSnapshot) {
                groups.value = (dataSnapshot.children.map { c ->
                    // Get group data (without key)
                    val group = c.getValue(SearchGroupData::class.java)
                    // Retrieve group key generated by google and use it
                    group?.uuid = c.key
                    group!!
                })
            }

            override fun onCancelled(error: DatabaseError) {
                // Failed to read value
                Timber.w("Failed to read value.")
            }
        })
        return groups
    }

    override fun getGroupById(groupId: String): MutableLiveData<SearchGroupData> {
        if (!watchedGroupsById.containsKey(groupId)) {
            val myRef = database.getReference("search_groups/$groupId")
            watchedGroupsById[groupId] = MutableLiveData()
            //TODO change to childEventListener ?
            myRef.addValueEventListener(object : ValueEventListener {
                override fun onDataChange(dataSnapshot: DataSnapshot) {
                    val group = dataSnapshot.getValue(SearchGroupData::class.java)
                    group?.uuid = dataSnapshot.key
                    watchedGroupsById[groupId]!!.value = group
                }

                override fun onCancelled(error: DatabaseError) {
                    Timber.w("Failed to read group from firebase.")
                }
            })
        }
        return watchedGroupsById[groupId]!!
    }

    /**
     * Creates a group with the given data.
     * The uuid of the searchgroup data will be overridden by an automatically generated one.
     */
    override fun createGroup(searchGroupData: SearchGroupData) {
        val myRef = database.getReference("search_groups")
        myRef.push().setValue(searchGroupData)
    }

    override fun updateGroup(searchGroupData: SearchGroupData) {
        val myRef = database.getReference("search_groups/${searchGroupData.uuid}")
        myRef.setValue(searchGroupData)
    }
}